### ISSUE TITLE
Eigenschaft der Räume: Unterscheidung zwischen Smartlock, Raum offen, Raum wird geöffnet

### ISSUE THREAD

**Issue by AvitusMaximus** [christian-vorhemus/Room2Go#1]
Die Vermieter müssen angeben, ob der Raum zur Zeit der Buchung ständig offen steht (z.B. Seminarräume in einem Hotel), ob sie bei Buchung extra von jemanden aufgesperrt werden (z.B. Geschäftslokal oder Lagerraum in einem Einfamilienhaus - in diesem Fall muss eine Telefonnummer hinterlegt werden) oder ob sie ein Smartlock von Nuki installieren.
Für die Mieter muss das klar bei der Raumbeschreibung deutlich gekennzeichnet sein.
Eine Filterfunktion ist hier nicht notwendig.

**Comment by christian-vorhemus** [comment]
Zwei Optionen: Jemand öffnet Tür oder Smartlock
