### ISSUE TITLE
Oberfläche: Vermieter müssen ebenfalls eine Mieter-Ansicht wählen können und umgekehrt

### ISSUE THREAD

**Issue by AvitusMaximus** [christian-vorhemus/Room2Go#2]
Die Vermieter müssen ebenfalls eine Mieter-Ansicht wählen können und natürlich auch umgekehrt.
Als Vermieter muss man auch die Option "Tür öffnen" bekommen - ohne den Raum buchen zu müssen. Sollte zur Zeit eine aktive Buchung sein, muss der Vermieter mit einer Warnung darauf hingewiesen werden, dass er hier ggf. die Privatsphäre des Mieters stört und dieser das Geld zurückfordern kann.

**Comment by christian-vorhemus** [comment]
Sollte keine core priority sein, da die typischen Vermieter wohl keine Mieter sind. Ist auch nicht so leicht umsetzbar, da Vermieter einige Dinge nicht müssen, die Mieter müssen (zB ID hochladen). Dh, wenn, dann muss ein Vermieter sowieso einen Mieter-Account anlegen wenn er mieten will. Worüber man nachdenken kann ist, einen Vermieter- und Mieter-Account verknüpfbar zu machen. Bis dahin kann ein Vermieter als Workaround auch einen Mieter-Account anlegen.

**Comment by AvitusMaximus** [comment]
JEDER ist ein potentieller Mieter. Und des weiteren wollen wir doch bei Vorführungen ganz easy beides herzeigen ohne erst auszuloggen um mit einem anderen Account einzuloggen.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.08.17, 10:44, christian-vorhemus <notifications@github.com> schrieb:
Sollte keine core priority sein, da die typischen Vermieter wohl keine Mieter sind. Ist auch nicht so leicht umsetzbar, da Vermieter einige Dinge nicht müssen, die Mieter müssen (zB ID hochladen). Dh, wenn, dann muss ein Vermieter sowieso einen Mieter-Account anlegen wenn er mieten will. Worüber man nachdenken kann ist, einen Vermieter- und Mieter-Account verknüpfbar zu machen. Bis dahin kann ein Vermieter als Workarround auch einen Mieter-Account anlegen.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/christian-vorhemus/Room2Go","title":"christian-vorhemus/Room2Go","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/christian-vorhemus/Room2Go"}},"updates":{"snippets":[{"icon":"PERSON","message":"@christian-vorhemus in #2: Sollte keine core priority sein, da die typischen Vermieter wohl keine Mieter sind. Ist auch nicht so leicht umsetzbar, da Vermieter einige Dinge nicht müssen, die Mieter müssen (zB ID hochladen). Dh, wenn, dann muss ein Vermieter sowieso einen Mieter-Account anlegen wenn er mieten will. Worüber man nachdenken kann ist, einen Vermieter- und Mieter-Account verknüpfbar zu machen. Bis dahin kann ein Vermieter als Workarround auch einen Mieter-Account anlegen."}],"action":{"name":"View Issue","url":"https://github.com/christian-vorhemus/Room2Go/issues/2#issuecomment-323296759"}}}
