### ISSUE TITLE
Liste Reservierungen

### ISSUE THREAD

**Issue by Ilvie** [christian-vorhemus/Room2Go#31]
reservierte Räume per Klick nochmal einsehbar, als Rembember

**Comment by christian-vorhemus** [comment]
Zusätzlich dazu sollte, sobald der Zeitpunkt erreicht ist an dem die Miete startet, auf dieser Seite ein "Tür öffnen" Button angezeigt werden. Davor soll ein Feld erscheinen "Du hast diesen Raum für den XX.XX.XXXX um XX:XX gebucht"

**Comment by christian-vorhemus** [comment]
Erledigt
